# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfd7019c68d3d789400fc3fcad338fe4bd5983b31d0eba76e1b61c155203dbbf95a3d50b41bbf41cd6d8231e95f5241b9ac89d7864d39a831aff99f5b0447792

test:
  secret_key_base: 67d4095724191421c6362709c765e6dda97496dd140b0c1fbdd09a6d0281f9d17b65975333f64bed3309d0db2793bcda8082bfc223ea57cc8629d47e15c2a28e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
